services:
  mysql:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=churchlinkhub
      - MYSQL_PASSWORD=mysqlserver
      - MYSQL_USER=churchlink
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db:/var/lib/mysql
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  flask:
    build: .
    container_name: flask
    restart: always
    environment:
        - DATABASE_URL=mysql+pymysql://churchlink:mysqlserver@dbserver/churchlinkhub
    volumes:
      - ./app:/home/churchlinkhub/app:ro
      - ./migrations:/home/churchlinkhub/migrations:rw
      - ./churchlinkhub.py:/home/churchlinkhub/churchlinkhub.py:ro
      - ./wsgi.py:/home/churchlinkhub/wsgi.py:ro
      - ./config.py:/home/churchlinkhub/config.py:ro
     # - ./boot.sh:/home/churchlinkhub/boot.sh:ro
    depends_on:
      - mysql
    links:
      - mysql:dbserver
